markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /bayesian-learning/:categories/:year/:month/:day/:title/

# Setup
title:            Bayesian Learning
tagline:          'A Jekyll theme'
description:      'A study for bayesian learning'
url:              https://rose-j.github.io/
baseurl:          /bayesian-learning/
    

author:
  name:           'Rose-J'
  url:            

paginate:         5



github:
  repo:           https://github.com/Rose-J/Rose-J.github.io
  bayesian:       https://github.com/Rose-J/bayesian-learning
